const configOptions = {
  mutate: [
    "src/lib/reminders/schema.ts",
    "src/lib/reminders/messages.ts",
    "src/lib/reminders/config.ts",
    "src/lib/reminders/http.ts",
    "src/lib/reminders/email-provider.ts",
    "src/lib/reminders/email-webhook.ts",
    "src/lib/reminders/worker.ts",
    "src/lib/reminders/operations.ts",
    "src/lib/reminders/repository.ts",
    "src/app/practice/reminders/actions.ts",

    "src/lib/sms/schema.ts",
    "src/lib/sms/repository.ts",
    "src/lib/sms/operations.ts",
    "src/lib/sms/messages.ts",
    "src/lib/sms/provider.ts",
    "src/lib/sms/config.ts",
    "src/lib/sms/disclosures.ts",
    "src/lib/sms/webhook.ts",
    "src/app/practice/sms/actions.ts",
    "src/lib/dashboard/summary.ts",
    "src/lib/calendar/events.ts",
    "src/lib/calendar/dates.ts",
    "src/lib/calendar/query.ts",
    "src/lib/practice/schema.ts",
    "src/lib/practice/timezones.ts",
    "src/lib/practice/repository.ts",
    "src/lib/practice/save.ts",
    "src/lib/auth/operations.ts",
    "src/app/practice/actions.ts",
    "src/app/login/actions.ts",
    "src/lib/practice/access.ts",
    "src/lib/team/schema.ts",
    "src/lib/recipients/schema.ts",
    "src/lib/register/schema.ts",
    "src/lib/register/dates.ts",
    "src/lib/register/operations.ts",
    "src/lib/register/repository.ts",
    "src/lib/register/messages.ts",
    "src/app/practice/register/actions.ts",
    "src/lib/recipients/operations.ts",
    "src/lib/recipients/repository.ts",
    "src/lib/recipients/messages.ts",
    "src/app/practice/recipient-actions.ts",
    "src/lib/team/invitations.ts",
    "src/lib/team/repository.ts",
    "src/lib/team/operations.ts",
    "src/lib/team/messages.ts",
    "src/app/practice/team/actions.ts",
    "src/app/join/actions.ts",
  ],
  ignorePatterns: [
    "/reports",
    "/coverage",
    "/test-results",
    "/playwright-report",
    "/.browser-cache",
    "/.venv-gauntlet",
    "/.tools",
    "/.tools/**",
    "/.browser-cache/**",
    "/.venv-gauntlet/**",
    "/.next/**",
    "/coverage/**",
    "/test-results/**",
    "/playwright-report/**",
  ],
  testRunner: "vitest",
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  vitest: { configFile: "vitest.mutation.config.ts" },
  reporters: ["clear-text", "json", "html"],
  jsonReporter: { fileName: "reports/mutation.json" },
  htmlReporter: { fileName: "reports/mutation.html" },
  coverageAnalysis: "off",
  concurrency: 4,
  thresholds: { high: 100, low: 100, break: 100 },
  timeoutMS: 10000,
};

export default configOptions;
