const configOptions = {
  mutate: [
    "src/lib/practice/schema.ts",
    "src/lib/practice/timezones.ts",
    "src/lib/practice/repository.ts",
    "src/lib/practice/save.ts",
    "src/lib/auth/operations.ts",
    "src/app/practice/actions.ts",
    "src/app/login/actions.ts",
    "src/lib/practice/access.ts",
    "src/lib/team/schema.ts",
    "src/lib/team/invitations.ts",
    "src/lib/team/repository.ts",
    "src/lib/team/operations.ts",
    "src/lib/team/messages.ts",
    "src/app/practice/team/actions.ts",
    "src/app/join/actions.ts",
  ],
  ignorePatterns: [
    "/reports",
    "/coverage",
    "/test-results",
    "/playwright-report",
    "/.browser-cache",
    "/.venv-gauntlet",
    "/.tools",
    "/.tools/**",
    "/.browser-cache/**",
    "/.venv-gauntlet/**",
    "/.next/**",
    "/coverage/**",
    "/test-results/**",
    "/playwright-report/**",
  ],
  testRunner: "vitest",
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  vitest: { configFile: "vitest.mutation.config.ts" },
  reporters: ["clear-text", "json", "html"],
  jsonReporter: { fileName: "reports/mutation.json" },
  htmlReporter: { fileName: "reports/mutation.html" },
  coverageAnalysis: "off",
  concurrency: 4,
  thresholds: { high: 100, low: 100, break: 100 },
  timeoutMS: 10000,
};

export default configOptions;
